name: Castor

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Castor
      uses: ZtModArchive/Castor-Build-Action@1.0.0-beta.3
    - uses: xresloader/upload-to-github-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.z2f;*.zip;"
        update_latest_release: true
        overwrite: true
        verbose: true
